### PR TITLE
Create guinea-connect.md

### PR DESCRIPTION
**Pull request by cristinasantamarina**
Do not merge - WIP

### CODE REVIEW

**Comment by admbtlr** [comment]
As long as you add `draft: true` to the front matter at the top of the file, you can safely merge this without it appearing on the actual site. See, for example, the [EOC Dashboard case study](https://github.com/eHealthAfrica/eHealthAfrica.github.io/blob/master/_case-studies/eoc-dashboard.md). 

You can then see it by going directly to the URL ([eg.](http://ehealthafrica.github.io/case-studies/eoc-dashboard.html)), but it won't appear in the [listing](http://ehealthafrica.github.io/case-studies.html).

Looking good, btw :)

**Comment by cristinasantamarina** [comment]
@ManuelLoistl WIP for your review

**Comment by cristinasantamarina** [comment]
@adamvert I merged and marked as draft but can not see at http://ehealthafrica.github.io/case-studies/guinea-connect.html

What did i do wrong :) ?

**Comment by cristinasantamarina** [comment]
@adamvert forget it - being too impatient. That's what!

**Comment by admbtlr** [comment]
You have to give Github a moment to catch up

**Pull request merged**
